spring.application.name=ai-support-ticket-triage-api

spring.datasource.url=jdbc:postgresql://localhost:5432/ai_support_ticket_triage
spring.datasource.username=ai_support_ticket_triage
spring.datasource.password=ticket@26
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
