spring.application.name=ai-support-ticket-triage-api

spring.ai.google.genai.api-key=${OPENAI_API_KEY}
spring.ai.google.genai.chat.model=gemini-3.6-flash

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Auto-update database schema on deployment
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
